development: &development
  database: lubn_development
  host: localhost
  adapter: postgresql
  encoding: utf8
  pool: 10
  username: <%= Rails.application.credentials[:development][:database][:username] %>
  password: <%= Rails.application.credentials[:development][:database][:password] %>

test:
  <<: *development
  database: lubn_test

preparing:
  <<: *development
  database: lubn_preparing
  username: <%= Rails.application.credentials[:preparing][:database][:username] %>
  password: <%= Rails.application.credentials[:preparing][:database][:password] %>